//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sclera2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Track
    {
        public int ID { get; set; }
        public string track_name { get; set; }
        public Nullable<int> GearID { get; set; }
        public Nullable<int> survey_response_id { get; set; }
    
        public virtual Gear Gear { get; set; }
        public virtual Survey_Response Survey_Response { get; set; }
    }
}
